### ISSUE TITLE
Program cannot redirect from page login to login-check

### ISSUE THREAD

**Issue by TonyisHero01** [TonyisHero01/Bachelor_thesis#1]
When I wrote http://localhost:81/76824974/eshop_cms/login in the browser, it showed the login page. When I clicked the Login button after filling out the form. It cannot redirect to the login-check file as I expected.

**Comment by skodapetr** [comment]
Why do you employ JS to do the redirect, why not return Location header with 302 from PHP?

In general, I see reasons why to employ JS but .. I fail to see them in context of the current codebase.
